### ISSUE TITLE
Changing License

### ISSUE THREAD

**Issue by R4356th** [snapwiki/SnapWikiSkin-OLD#10]
MIT license is not good if someone wants others not to use it without permission. We could use GPL or AGPL to be stricter but they do not have this condition, too.

**Comment by GrahamSH-LLK** [comment]
This is mostly from scratchwikiskin2, which uses it. We need a compatible license.

**Comment by R4356th** [comment]
Most of the licenses are compatible with MIT license due to the fact that it is extremely permissible.

**Comment by R4356th** [comment]
Both GPL and AGPL are compatible and I am in awe of GPL. What do you say?

**Comment by R4356th** [comment]
@GrahamSH-LLK ???

**Comment by GrahamSH-LLK** [comment]
Sorry. I don't mind either. You can pick.

**Comment by R4356th** [comment]
Okay. I am picking GPL.
